// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_HISTORY_LESH_UI_HISTORY_FB_H_
#define FLATBUFFERS_GENERATED_HISTORY_LESH_UI_HISTORY_FB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace lesh {
namespace ui {
namespace history {
namespace fb {

struct Record;
struct RecordBuilder;

struct HistoryFile;
struct HistoryFileBuilder;

struct Record FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RecordBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CMD = 4,
    VT_WHEN = 6,
    VT_CWD = 8,
    VT_EXIT_CODE = 10,
    VT_SESSION_ID = 12
  };
  const ::flatbuffers::Vector<uint8_t> *cmd() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_CMD);
  }
  uint64_t when() const {
    return GetField<uint64_t>(VT_WHEN, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *cwd() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_CWD);
  }
  int32_t exit_code() const {
    return GetField<int32_t>(VT_EXIT_CODE, 0);
  }
  uint64_t session_id() const {
    return GetField<uint64_t>(VT_SESSION_ID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_CMD) &&
           verifier.VerifyVector(cmd()) &&
           VerifyField<uint64_t>(verifier, VT_WHEN, 8) &&
           VerifyOffset(verifier, VT_CWD) &&
           verifier.VerifyVector(cwd()) &&
           VerifyField<int32_t>(verifier, VT_EXIT_CODE, 4) &&
           VerifyField<uint64_t>(verifier, VT_SESSION_ID, 8) &&
           verifier.EndTable();
  }
};

struct RecordBuilder {
  typedef Record Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cmd(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> cmd) {
    fbb_.AddOffset(Record::VT_CMD, cmd);
  }
  void add_when(uint64_t when) {
    fbb_.AddElement<uint64_t>(Record::VT_WHEN, when, 0);
  }
  void add_cwd(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> cwd) {
    fbb_.AddOffset(Record::VT_CWD, cwd);
  }
  void add_exit_code(int32_t exit_code) {
    fbb_.AddElement<int32_t>(Record::VT_EXIT_CODE, exit_code, 0);
  }
  void add_session_id(uint64_t session_id) {
    fbb_.AddElement<uint64_t>(Record::VT_SESSION_ID, session_id, 0);
  }
  explicit RecordBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Record> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Record>(end);
    fbb_.Required(o, Record::VT_CMD);
    return o;
  }
};

inline ::flatbuffers::Offset<Record> CreateRecord(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> cmd = 0,
    uint64_t when = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> cwd = 0,
    int32_t exit_code = 0,
    uint64_t session_id = 0) {
  RecordBuilder builder_(_fbb);
  builder_.add_session_id(session_id);
  builder_.add_when(when);
  builder_.add_exit_code(exit_code);
  builder_.add_cwd(cwd);
  builder_.add_cmd(cmd);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Record> CreateRecordDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *cmd = nullptr,
    uint64_t when = 0,
    const std::vector<uint8_t> *cwd = nullptr,
    int32_t exit_code = 0,
    uint64_t session_id = 0) {
  auto cmd__ = cmd ? _fbb.CreateVector<uint8_t>(*cmd) : 0;
  auto cwd__ = cwd ? _fbb.CreateVector<uint8_t>(*cwd) : 0;
  return lesh::ui::history::fb::CreateRecord(
      _fbb,
      cmd__,
      when,
      cwd__,
      exit_code,
      session_id);
}

struct HistoryFile FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef HistoryFileBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RECORDS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<lesh::ui::history::fb::Record>> *records() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<lesh::ui::history::fb::Record>> *>(VT_RECORDS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_RECORDS) &&
           verifier.VerifyVector(records()) &&
           verifier.VerifyVectorOfTables(records()) &&
           verifier.EndTable();
  }
};

struct HistoryFileBuilder {
  typedef HistoryFile Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_records(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<lesh::ui::history::fb::Record>>> records) {
    fbb_.AddOffset(HistoryFile::VT_RECORDS, records);
  }
  explicit HistoryFileBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<HistoryFile> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<HistoryFile>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<HistoryFile> CreateHistoryFile(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<lesh::ui::history::fb::Record>>> records = 0) {
  HistoryFileBuilder builder_(_fbb);
  builder_.add_records(records);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<HistoryFile> CreateHistoryFileDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<lesh::ui::history::fb::Record>> *records = nullptr) {
  auto records__ = records ? _fbb.CreateVector<::flatbuffers::Offset<lesh::ui::history::fb::Record>>(*records) : 0;
  return lesh::ui::history::fb::CreateHistoryFile(
      _fbb,
      records__);
}

inline const lesh::ui::history::fb::HistoryFile *GetHistoryFile(const void *buf) {
  return ::flatbuffers::GetRoot<lesh::ui::history::fb::HistoryFile>(buf);
}

inline const lesh::ui::history::fb::HistoryFile *GetSizePrefixedHistoryFile(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<lesh::ui::history::fb::HistoryFile>(buf);
}

inline const char *HistoryFileIdentifier() {
  return "SHH1";
}

inline bool HistoryFileBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, HistoryFileIdentifier());
}

inline bool SizePrefixedHistoryFileBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, HistoryFileIdentifier(), true);
}

template <bool B = false>
inline bool VerifyHistoryFileBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<lesh::ui::history::fb::HistoryFile>(HistoryFileIdentifier());
}

template <bool B = false>
inline bool VerifySizePrefixedHistoryFileBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<lesh::ui::history::fb::HistoryFile>(HistoryFileIdentifier());
}

inline void FinishHistoryFileBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<lesh::ui::history::fb::HistoryFile> root) {
  fbb.Finish(root, HistoryFileIdentifier());
}

inline void FinishSizePrefixedHistoryFileBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<lesh::ui::history::fb::HistoryFile> root) {
  fbb.FinishSizePrefixed(root, HistoryFileIdentifier());
}

}  // namespace fb
}  // namespace history
}  // namespace ui
}  // namespace lesh

#endif  // FLATBUFFERS_GENERATED_HISTORY_LESH_UI_HISTORY_FB_H_
